### ISSUE TITLE
which g4  version you were used?

### ISSUE THREAD

**Issue by NuaaMtz** [fzenoni/TrGEMG4#1]
I want to run your project in my server. when i try to run command "make",the terminal reported  as follow:
```
/usr/bin/ld: CMakeFiles/TrGEMG4.dir/src/TrGEMTrackingAction.cc.o:(.data.rel.ro._ZTV19TrGEMTrackingAction[_ZTV19TrGEMTrackingAction]+0x20): undefined reference to `TrGEMTrackingAction::SetTrackingManagerPointer(G4TrackingManager*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/TrGEMG4.dir/build.make:526: TrGEMG4] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/TrGEMG4.dir/all] Error 2
```
Maybe cause by the version of g4.If possible please help me. It's similar with my work.By the way,I am using geant4 with version11.0.0 and 11.0.4.  Thank you very much~~~!

**Comment by flzenoni** [comment]
Hi @NuaaMtz, I had to check on my thesis (available [here](https://iihe.ac.be/sites/default/files/thesis-florian-zenoni-phd-2016pdf/thesis-florian-zenoni-phd-2016.pdf)) because I hadn't worked on this project since 2016. The version that I used at the time should be [Geant4 10.1.patch2](https://geant4.org/download/10.1.2.html). I hope this can help you.

**Comment by fzenoni** [comment]
Hi @NuaaMtz. I had to check on my Phd thesis (available [here](https://iihe.ac.be/sites/default/files/thesis-florian-zenoni-phd-2016pdf/thesis-florian-zenoni-phd-2016.pdf)) because I haven't touched this project since 2016. The version I used should be [Geant4 10.1.patch2](https://geant4.org/download/10.1.2.html). I hope this can help you.

**Comment by NuaaMtz** [comment]
@fzenoni Thank you very much for your help. I tried using geant4 10.1.2, and I have successfully run this project. Your PHD thesis has been very helpful to me as well. Thanks once more for your assistance!!!~~~
